apiVersion: v1
kind: Service
metadata:
  name: {{ include "factorio.fullname" . }}
  labels:
    {{- include "factorio.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.factorioServer.port }}
      targetPort: {{ .Values.factorioServer.port }}
      protocol: UDP
      name: factorio
    {{- if .Values.factorioServer.rcon.enabled }}
    - port: {{ .Values.factorioServer.rcon.port }}
      targetPort: {{ .Values.factorioServer.rcon.port }}
      protocol: TCP
      name: rcon
    {{- end }}
  selector:
    {{- include "factorio.selectorLabels" . | nindent 4 }}